### ISSUE TITLE
npm ERR! 404 Not Found: gentelella_admin@latest

### ISSUE THREAD

**Issue by jjramosj** [puikinsh/gentelella#733]
Hi!

Just to let you know that I am trying to install gentelella through npm and I get this error:

`npm ERR! 404 Not Found: gentelella_admin@latest`

This is the log file

```
 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gentelella_admin',
1 verbose cli   '--save' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session 486aecfdcd6d8073
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/gentelella_admin 909ms
8 silly fetchPackageMetaData error for gentelella_admin@latest 404 Not Found: gentelella_admin@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 1138ms
11 verbose stack Error: 404 Not Found: gentelella_admin@latest
11 verbose stack     at fetch.then.res (E:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (E:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:693:18)
11 verbose stack     at tryOnImmediate (timers.js:664:5)
11 verbose stack     at processImmediate (timers.js:646:5)
12 verbose cwd E:\AppServ\www\admin templates\comunica_admin
13 verbose Windows_NT 10.0.17134
14 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gentelella_admin" "--save"
15 verbose node v10.9.0
16 verbose npm  v6.2.0
17 error code E404
18 error 404 Not Found: gentelella_admin@latest
19 verbose exit [ 1, true ]
```

**Comment by AndreiCN** [comment]
"npm install gentelella --save" and you will get no errors.
